DROP DATABASE IF EXISTS Aeroporto;

CREATE DATABASE Aeroporto;

USE Aeroporto;

CREATE TABLE CIDADE(
	IDCIDADE INT(4) NOT NULL,
	PAIS VARCHAR(15) NOT NULL,
	NOMECIDADE VARCHAR(20) NOT NULL,
	PRIMARY KEY(IDCIDADE)
);

CREATE TABLE AEROPORTO(
	IDAEROPORTO VARCHAR(9) NOT NULL,
	NOMEAEROPORTO VARCHAR(100) NOT NULL,
	PRIMARY KEY(IDAEROPORTO)
);

CREATE TABLE VOO(
	NUMERO INT(4) NOT NULL,
	PRIMARY KEY(NUMERO)
);

CREATE TABLE COMPANHIA_AEREA(
	IDCOMPANHIA VARCHAR(8) NOT NULL,
	NOMECOMP VARCHAR(30) NOT NULL,
	CNPJ CHAR(9) NOT NULL,
	TELEFONE CHAR(8) NOT NULL,
	EMAIL CHAR(30) NOT NULL,
	PRIMARY KEY(IDCOMPANHIA),
	UNIQUE KEY (CNPJ)
);

CREATE TABLE AVIAO(
	IDAVIAO INT(5) NOT NULL,
	TIPOAVIAO VARCHAR(20),
	NUMEROASSENTOS INT,
	NUMEROVOO INT NOT NULL,
	PRIMARY KEY(IDAVIAO),
	FOREIGN KEY (NUMEROVOO) REFERENCES VOO(NUMERO) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);

CREATE TABLE FUNCIONARIOS(
	IDFUNCIONARIO INT(3) NOT NULL,
	PNOME VARCHAR(15) NOT NULL,
	MNOME CHAR,
	SNOME VARCHAR(15) NOT NULL,
	DOCUMENTO CHAR(12) NOT NULL,
	IDIOMA CHAR(20), 
	SEXO CHAR,
	TIPO CHAR(15),
	COMPANHIA VARCHAR(8) NOT NULL,
	PRIMARY KEY(IDFUNCIONARIO),
	UNIQUE KEY(DOCUMENTO),
	FOREIGN KEY(COMPANHIA) REFERENCES COMPANHIA_AEREA(IDCOMPANHIA) 	
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);

CREATE TABLE PILOTO(
	IDPILOTO INT(6) NOT NULL,
	HORASVOO INT NOT NULL,
	IDFUNC INT(3) NOT NULL,
	PRIMARY KEY(IDPILOTO),
	FOREIGN KEY(IDFUNC) REFERENCES FUNCIONARIOS(IDFUNCIONARIO)
	 ON DELETE CASCADE
	 ON UPDATE CASCADE
);

CREATE TABLE COMISSARIO(
	IDCOMISSARIO INT(6) NOT NULL,
	IDFUNC INT(3) NOT NULL,
	PRIMARY KEY(IDCOMISSARIO),
	FOREIGN KEY(IDFUNC) REFERENCES FUNCIONARIOS(IDFUNCIONARIO) 
		ON DELETE CASCADE
		ON UPDATE CASCADE 
);

CREATE TABLE TRECHO(
	IDTRECHO INT(4) NOT NULL,
	NVOO INT(4) NOT NULL,
	IDA INT(5) NOT NULL,
	IDP INT(6) NOT NULL,
	IDC INT(6) NOT NULL,
	PRIMARY KEY(IDTRECHO),
	FOREIGN KEY(NVOO) REFERENCES VOO(NUMERO) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE,
	FOREIGN KEY(IDA) REFERENCES AVIAO(IDAVIAO) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE,
	FOREIGN KEY(IDP) REFERENCES PILOTO(IDPILOTO) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE,
	FOREIGN KEY(IDC) REFERENCES COMISSARIO(IDCOMISSARIO) 
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE PASSAGEIRO(
	PNOME VARCHAR(15) NOT NULL,
	MNOME CHAR,
	SNOME VARCHAR(15) NOT NULL,
	PASSAPORTE VARCHAR(11) NOT NULL,
	IDADE INT(2),
	NVOOP INT(4) NOT NULL,
	PRIMARY KEY(PASSAPORTE),
	FOREIGN KEY(NVOOP) REFERENCES VOO(NUMERO) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);